### ISSUE TITLE
Cross section plugin crashes if mouse enters a plot object it's not happy with

### ISSUE THREAD

**Issue by raacampbell** [SainsburyWellcomeCentre/lasagna#196]
Steps to reproduce:
Start Lasagna. Load a stack. Start the tutorial plugin "Cross section plugin". Mouse over the images fairly rapidly, leaving and entering the axes. Quickly Lasagna will crash and generate the error:

```
ind_pyqt_graph_object_name_in_plot_widget finds no attribute getPlotItem
Error running plugin method <bound method plugin.hook_updateMainWindowOnMouseMove_End of <cross_section_plugin.plugin object at 0x11c4b23a8>>; main error 'NoneType' object has no attribute 'parent'
Traceback (most recent call last):
  File "/Users/rob/Dropbox (UCL - SWC)/work/Anatomy/code/lasagna/lasagna/lasagna_object.py", line 1147, in mouseMoved
    self.updateMainWindowOnMouseMove(self.axes2D[axis_id])
  File "/Users/rob/Dropbox (UCL - SWC)/work/Anatomy/code/lasagna/lasagna/lasagna_object.py", line 914, in updateMainWindowOnMouseMove
    self.runHook(self.hooks['updateMainWindowOnMouseMove_End'])  # Runs each time the views are updated
  File "/Users/rob/Dropbox (UCL - SWC)/work/Anatomy/code/lasagna/lasagna/lasagna_object.py", line 313, in runHook
    hook(*args)
  File "/Users/rob/work/Anatomy/code/lasagna/lasagna/plugins/tutorial_plugins/cross_section_plugin.py", line 44, in hook_updateMainWindowOnMouseMove_End
    plot_widget = qApp.widgetAt(pos).parent()  # The mouse is in this widget
AttributeError: 'NoneType' object has no attribute 'parent'
Abort trap: 6
```

**Comment by raacampbell** [comment]
Seems to happen when the user moves the mouse quickly out of the Lasagna window. There is a lag between registering the mouse motion and reading where it is. I tried bailing out if it encounters class
 "NoneType" by doing:

```
        # Get the widget that the mouse is currently in
        pos = QtGui.QCursor.pos()
        if str(type(pos)) == "<class 'NoneType'>":
            print("\n\nBAILING OUT\n\n")
            return
```

But it does not show the string when it crashes and instead I get:

```
raceback (most recent call last):
  File "/Users/rob/Dropbox (UCL - SWC)/work/Anatomy/code/lasagna/lasagna/lasagna_object.py", line 1387, in mouseMoved
    self.updateMainWindowOnMouseMove(self.axes2D[axis_id])
  File "/Users/rob/Dropbox (UCL - SWC)/work/Anatomy/code/lasagna/lasagna/lasagna_object.py", line 1101, in updateMainWindowOnMouseMove
    self.hooks["updateMainWindowOnMouseMove_End"]
  File "/Users/rob/Dropbox (UCL - SWC)/work/Anatomy/code/lasagna/lasagna/lasagna_object.py", line 418, in runHook
    hook(*args)
  File "/Users/rob/work/Anatomy/code/lasagna/lasagna/plugins/tutorial_plugins/cross_section_plugin.py", line 59, in hook_updateMainWindowOnMouseMove_End
    plot_widget, itemName=selected_stack_name, regex=True
  File "/Users/rob/Dropbox (UCL - SWC)/work/Anatomy/code/lasagna/lasagna/utils/lasagna_qt_helper_functions.py", line 51, in find_pyqt_graph_object_name_in_plot_widget
    if re.search(itemName, item.objectName):
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

**Comment by raacampbell** [comment]
Seems tricky. I think we need a better way to figure out in which window the mouse was in.
