### ISSUE TITLE
Elastix plugin: Cannot load parameter files

### ISSUE THREAD

**Issue by ablot** [SainsburyWellcomeCentre/lasagna#239]
When trying to load any parameter file, the elastix plugin crashes (traceback below). The error comes from `QtGui.QFileDialog.getOpenFileNames` which, for me, returns the file list AND the filter selected. @raacampbell does the plugin work for you as is? 

`Traceback (most recent call last):
  File "/home/blota/Code/Python/Anatomy/lasagna/lasagna/plugins/registration_plugins/elastix_plugin.py", line 323, in loadParamFile_slot
    shutil.copyfile(path_to_param_file, self.tmpParamFiles[param_file_name])
  File "/home/blota/Software/anaconda3/envs/lasagna/lib/python3.7/shutil.py", line 103, in copyfile
    if _samefile(src, dst):
  File "/home/blota/Software/anaconda3/envs/lasagna/lib/python3.7/shutil.py", line 88, in _samefile
    return os.path.samefile(src, dst)
  File "/home/blota/Software/anaconda3/envs/lasagna/lib/python3.7/genericpath.py", line 96, in samefile
    s1 = os.stat(f1)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not list
`

**Comment by ablot** [comment]
Would PR #240 break your setup @raacampbell ? If so we might have to play with Qt versions...
I use 
Qt version: 5.12.2
SIP version: 4.19.15
PyQt version: 5.12.1

**Comment by raacampbell** [comment]
I will try tomorrow if I get a chance. Ping me back if I don't do it.

**Comment by apdals** [comment]
I am using the master branch and have been receiving the same error as @ablot. I know that this issue was addressed and the code was changed in the development branch. I also see that the dev branch has been merged with the master branch not long ago. However, after looking through the code in the master branch, the change is no longer present. Was the change passed on? Was there a reason why the change was removed in the master? Thanks.

**Comment by nsteinme** [comment]
hey @raacampbell, @apdals is in my lab and we're stuck moving forward with lasagna because of this error. Any ideas of what we're doing wrong? Are other labs in IBL not having this problem, should we talk with Steven West about it, would he be able to help us?

**Comment by raacampbell** [comment]
Is it necessary to use the Elastix plugin in Lasagna? We aren't doing it, actually. We are running Elastix via a MATLAB script: https://github.com/SainsburyWellcomeCentre/ara_tools the command is `ARAregister`

I know that doesn't address the issue of this Lasagna plugin not working but at the moment I don't have plans to fix it.

**Comment by nsteinme** [comment]
Thanks Rob - we had missed that. We'll try the matlab script. Might be worth adding a note about this here? https://github.com/SainsburyWellcomeCentre/lasagna/wiki/Elastix-Image-Registation-Plugin

**Comment by raacampbell** [comment]
Good point. I've added the info.
