### ISSUE TITLE
add_line_plugin does not work after fresh install

### ISSUE THREAD

**Issue by guidomeijer** [SainsburyWellcomeCentre/lasagna#250]
I recently switched from Anaconda to Mambaforge and reinstalled Lasagna from scratch using the instructions on the repo. However, now the add_line_plugin does not work anymore. Points do not appear and a string of errors appears in the terminal. 

I'm on Ubuntu and the version is Lasagna == 0.1.

```
lasanga.addIngredient - Adding sparsepoints ingredient: addLine_currentLine
Traceback (most recent call last):
  File "/home/guido/Repositories/lasagna/lasagna/lasagna_object.py", line 389, in startStopPlugin
    self.startPlugin(plugin_name)
  File "/home/guido/Repositories/lasagna/lasagna/lasagna_object.py", line 395, in startPlugin
    self.plugins[pluginName] = self.plugins[pluginName](
  File "/home/guido/Repositories/lasagna/lasagna/plugins/annotation_plugins/add_line_plugin.py", line 45, in __init__
    self.lasagna.addIngredient(
  File "/home/guido/Repositories/lasagna/lasagna/lasagna_object.py", line 654, in addIngredient
    ingredient_class_obj(
  File "/home/guido/Repositories/lasagna/lasagna/ingredients/sparsepoints.py", line 41, in __init__
    self.color = [color[0] * 255, color[1] * 255, color[2] * 255]
  File "/home/guido/Repositories/lasagna/lasagna/ingredients/sparsepoints.py", line 168, in set_color
    self.setRowColor()
  File "/home/guido/Repositories/lasagna/lasagna/ingredients/lasagna_ingredient.py", line 132, in setRowColor
    QC=QtGui.QColor(self.color[0], self.color[1], self.color[2])
TypeError: arguments did not match any overloaded call:
  QColor(Qt.GlobalColor): argument 1 has unexpected type 'numpy.float64'
  QColor(int): argument 1 has unexpected type 'numpy.float64'
  QColor(QRgba64): argument 1 has unexpected type 'numpy.float64'
  QColor(Any): too many arguments
  QColor(): too many arguments
  QColor(int, int, int, alpha: int = 255): argument 1 has unexpected type 'numpy.float64'
  QColor(str): argument 1 has unexpected type 'numpy.float64'
  QColor(Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'numpy.float64'
Error running plugin method <bound method plugin.hook_axisClicked of <add_line_plugin.plugin object at 0x7faeecbe7130>>; main error 'plugin' object has no attribute 'hPoint_name'
Traceback (most recent call last):
  File "/home/guido/Repositories/lasagna/lasagna/lasagna_object.py", line 1131, in axisClicked
    self.runHook(self.hooks["axisClicked"], self.axes2D[axis_id])
  File "/home/guido/Repositories/lasagna/lasagna/lasagna_object.py", line 434, in runHook
    hook(*args)
  File "/home/guido/Repositories/lasagna/lasagna/plugins/annotation_plugins/add_line_plugin.py", line 138, in hook_axisClicked
    hLightCoords = self.lasagna.returnIngredientByName(self.hPoint_name)._data
AttributeError: 'plugin' object has no attribute 'hPoint_name'
Traceback (most recent call last):
  File "/home/guido/Repositories/lasagna/lasagna/lasagna_object.py", line 621, in closeEvent
    self.quitLasagna()
  File "/home/guido/Repositories/lasagna/lasagna/lasagna_object.py", line 611, in quitLasagna
    ].confirmOnClose:  # TODO: handle cases where plugins want confirmation to close
AttributeError: type object 'plugin' has no attribute 'confirmOnClose'
Stopping add_line_plugin
failed to properly close plugin add_line_plugin; main error: plugin.closePlugin() missing 1 required positional argument: 'self'
```

Any help would be greatly appreciated!

**Comment by raacampbell** [comment]
Can you confirm if the problem happens with the version on the master
branch right now? It was updated last week.

**Comment by guidomeijer** [comment]
It works, thank you!
